<script setup>
import { Head, Link, useForm } from "@inertiajs/vue3";
import RoleDashboardLayout from "@/Layouts/RoleDashboardLayout.vue";

const form = useForm({
    name: "",
});

const submit = () => {
    form.post(route("floors.store"));
};
</script>

<template>
    <Head title="Create Floor" />

    <RoleDashboardLayout>
        <section
            class="h-full overflow-y-auto bg-gradient-to-br from-slate-100 via-slate-100 to-cyan-50/40"
        >
            <div class="mx-auto max-w-3xl px-6 py-8 md:py-10">
                <div
                    class="rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"
                >
                    <div
                        class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"
                    >
                        <div>
                            <p
                                class="text-[11px] font-semibold uppercase tracking-[0.35em] text-cyan-600"
                            >
                                Floor Setup
                            </p>
                            <h1
                                class="mt-2 text-3xl font-semibold text-slate-900"
                            >
                                Create Floor
                            </h1>
                        </div>

                        <Link
                            :href="route('floors.index')"
                            class="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-600 transition-colors duration-200 hover:bg-slate-50"
                        >
                            Back to Floors
                        </Link>
                    </div>

                    <form class="mt-8 space-y-6" @submit.prevent="submit">
                        <div>
                            <label
                                for="name"
                                class="mb-2 block text-sm font-medium text-slate-700"
                            >
                                Floor Name
                            </label>
                            <input
                                id="name"
                                v-model="form.name"
                                type="text"
                                placeholder="Example: First Floor"
                                class="w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-700 placeholder:text-slate-400 focus:border-cyan-300 focus:outline-none focus:ring-2 focus:ring-cyan-200/60"
                            />
                            <p
                                v-if="form.errors.name"
                                class="mt-2 text-sm text-rose-500"
                            >
                                {{ form.errors.name }}
                            </p>
                        </div>

                        <div
                            class="rounded-xl border border-slate-200 bg-slate-50 p-3 text-sm text-slate-600"
                        >
                            Floor number will be auto-generated by the system
                            (minimum 4 digits).
                        </div>

                        <div class="flex items-center justify-end gap-3 pt-2">
                            <Link
                                :href="route('floors.index')"
                                class="rounded-xl border border-slate-200 bg-white px-4 py-2.5 text-sm font-medium text-slate-600 transition-colors duration-200 hover:bg-slate-50"
                            >
                                Cancel
                            </Link>
                            <button
                                type="submit"
                                :disabled="form.processing"
                                class="rounded-xl border border-cyan-200 bg-cyan-50 px-4 py-2.5 text-sm font-semibold text-cyan-700 transition-colors duration-200 hover:bg-cyan-100 disabled:cursor-not-allowed disabled:opacity-50"
                            >
                                Save Floor
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </section>
    </RoleDashboardLayout>
</template>
